# Generated by Django 5.0.1 on 2024-01-08 10:37

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoTrap',
            fields=[
                ('mac_address', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ntp_server', models.CharField(default='http://pool.ntp.org/', max_length=255)),
                ('gmt_offset', models.IntegerField(default=-3)),
                ('daylight_offset', models.IntegerField(default=0)),
                ('movement_sensor', models.BooleanField(default=False)),
                ('restart', models.CharField(default='False', max_length=255)),
                ('photo_shooting_frequency', models.CharField(default='"12:00","24:00"', max_length=255)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('floor', models.FloatField(default=0.0)),
                ('server_url', models.CharField(default='192.168.0.1', max_length=255)),
                ('firmware_path', models.CharField(default='https://github.com/FernandoVinha/PhotoTrapFirmware', max_length=255)),
                ('install_new_firmware', models.BooleanField(default=False)),
                ('country', django_countries.fields.CountryField(default='BR', max_length=2)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.region')),
            ],
        ),
    ]
