# Generated by Django 4.2.7 on 2023-12-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('precision', models.PositiveSmallIntegerField()),
                ('_type', models.CharField(max_length=50)),
            ],
        ),
    ]
